<?php
    $data.="<aside>";
    $data.="<img src='img/fond.jpg' class='image'  alt='carte' />";
    $data.="<div>";
    $data.="<ul>" ;
    $data.="<li>Article</li>";
    $data.="<ul>";
    $data.= "<li> Saroumane </li>";
    $data.="<li> Elrond </li>" ;
    $data.="<li> Galadriel </li>";
    $data.="<li> Sylvebarbe </li>";
    $data.="<li> Gollum </li>";
    $data.="<li> Sauron </li>";
    $data.="</ul>";
    $data.="<li>Catégorie</li>";
    $data.="<ul>";
    $data.="<li> Homme </li>";
    $data.="<li> Elfe </li>" ;
    $data.="<li> Nain </li>" ;
    $data.="<li> Hobbit </li>";
    $data.="<li> Magicien </li>";
    $data.="<li> Créature </li>";
    $data.="</ul>";         
    $data.="<li>Contact: 12 rue des tournesols 69002 Lyon - Seigneur des anneaux Fan Site</li>";
    $data.="</ul>";
    $data.="</div>";
    $data.="</aside>";